### PR TITLE
Sarika/edit parse

### PR DESCRIPTION
**Pull request by sarikam1**
interactive elements implemented (with hard coded word suggestions)

### CODE REVIEW

**Comment by jaepark98** [comment]
Wait, this shouldn't be merged yet--I'm working on files from this merged to dev, and this is an untested version. Where are the functions you wrote specifically @sarikam1 ?

**Comment by mpcsh** [comment]
@sarikam1 for the future, you should never need to fork in this class - you have push access to this repo so you should be able to do all your development without a fork.

**Comment by mpcsh** [comment]
@sarikam1 also did you mean to merge this into master? This looks like it should go into dev.

**Comment by firatciftci** [comment]
I think we should merge this into dev and continue working on it before merging it into master.

**Comment by mpcsh** [comment]
@sarikam1 also, you should never tag someone who worked on the code with you for review, it defeats the purpose for review. You tagged Jae for review but it looks like he authored a number of these commits.

**Comment by mpcsh** [comment]
I'm actually going to go ahead and reject this now. This is an enormous diff and will be impossible to debug & merge properly. This shouldn't be merged into `dev` either. Cherry-pick the reasonable commits here (there are a few that stage small changes, and have descriptive commit messages) onto a new branch; the rest just redo. Submit a new PR to `dev` once tests pass.

**Pull request closed without merging**
